# Generated by Django 4.0.10 on 2023-10-04 21:01

from django.db import migrations, models
import django.db.models.deletion
import items_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0008_remove_districts_psc'),
        ('registration', '0004_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=25)),
                ('name_sk', models.CharField(max_length=25)),
                ('name_cz', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('create_time', models.DateTimeField(null=True)),
                ('active_time', models.DateTimeField()),
                ('title', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_list.categorylang')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.districts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=items_list.models.photo_path)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=25)),
                ('name_sk', models.CharField(max_length=25)),
                ('name_cz', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_list.categorylang')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('item', models.ManyToManyField(to='items_list.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ManyToManyField(to='items_list.photoitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.regions'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_list.subcategory'),
        ),
    ]
