# Generated by Django 4.0.10 on 2023-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=15)),
            ],
        ),
    ]
