# Generated by Django 4.0.10 on 2023-10-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photos',
        ),
    ]
