# Generated by Django 4.0.10 on 2023-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0002_remove_item_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ManyToManyField(to='items_list.photoitem'),
        ),
    ]
