# Generated by Django 4.0.10 on 2023-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
