# Generated by Django 4.0.10 on 2023-10-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0003_item_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneritem',
            name='item',
        ),
    ]
