# Generated by Django 4.0.10 on 2023-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0004_remove_partneritem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneritem',
            name='item',
            field=models.ManyToManyField(to='items_list.item'),
        ),
    ]
