# Generated by Django 4.0.10 on 2023-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0007_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=15)),
                ('name_sk', models.CharField(max_length=15)),
                ('name_cz', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
