# Generated by Django 4.0.10 on 2023-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0008_categorylang_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='name_cz',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='categorylang',
            name='name_en',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='categorylang',
            name='name_sk',
            field=models.CharField(max_length=25),
        ),
    ]
