# Generated by Django 4.0.10 on 2023-09-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0009_alter_categorylang_name_cz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=25)),
                ('name_sk', models.CharField(max_length=25)),
                ('name_cz', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_list.categorylang')),
            ],
        ),
    ]
