# Generated by Django 4.0.10 on 2023-09-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0011_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
