# Generated by Django 4.0.10 on 2023-09-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_districts_psc'),
        ('items_list', '0013_item_photoitem_partneritem_item_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
        ),
        migrations.AddField(
            model_name='item',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.districts'),
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.regions'),
        ),
    ]
