# Generated by Django 5.0.1 on 2024-02-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
        ('locations', '0003_remove_country_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
