# Generated by Django 5.0.1 on 2024-02-26 19:43

import icons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0002_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=icons.models.icon_path)),
            ],
        ),
    ]
