# Generated by Django 5.0.1 on 2024-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
