# Generated by Django 4.2.7 on 2023-12-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
