# Generated by Django 4.0.10 on 2023-08-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateTimeField(blank=True),
        ),
    ]
