# Generated by Django 4.2.7 on 2023-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_usermodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
