# Generated by Django 4.2.7 on 2023-12-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_usermodel_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_authenticated',
        ),
    ]
