# Generated by Django 4.0.10 on 2023-08-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
