# Generated by Django 4.2.7 on 2023-12-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_usermodel_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
