# Generated by Django 5.0.1 on 2024-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
