# Generated by Django 4.2.7 on 2023-12-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=''),
        ),
    ]
