# Generated by Django 4.2.7 on 2023-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_usermodel_first_name_usermodel_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
