# Generated by Django 4.0.10 on 2023-09-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
    ]
