# Generated by Django 5.0.1 on 2024-02-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='icon',
        ),
    ]
