# Generated by Django 4.0.10 on 2023-09-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_country_phone_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
