# Generated by Django 4.0.10 on 2023-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('coutry', models.ManyToManyField(to='locations.country')),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('psc', models.CharField(max_length=15)),
                ('region', models.ManyToManyField(to='locations.regions')),
            ],
        ),
    ]
