# Generated by Django 4.0.10 on 2023-09-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_regions_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='coutry',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
