# Generated by Django 4.0.10 on 2023-09-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_regions_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='psc',
        ),
    ]
